name: Release to Cloudelivery
on: 
  push:
    branches:
      - release

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout source code.
        uses: actions/checkout@master
            
      - name: Docker Image Build.
        uses: mr-smithers-excellent/docker-build-push@v2
        with:
          image: dimigo-asked
          tag: latest
          registry: docker.clou.delivery
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
